---
provisioner:
  name: chef_solo

driver_config:
  require_chef_omnibus: true

platforms:
  - name: va-centos-6.5
    driver:
      name: vagrant
      network:
        - ["private_network", {ip: "192.168.33.32"}]
      synced_folders:
        - ["vagrant", "/usr/share/nginx", "create: true, type: :nfs"]
    driver_config:
      box: opscode-centos-6.5
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
  - name: va-ubuntu-12.04
    driver:
      name: vagrant
      network:
        - ["private_network", {ip: "192.168.33.33"}]
      synced_folders:
        - ["vagrant", "/usr/share/nginx", "create: true, type: :nfs"]
    provider: virtualbox
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
      customize:
        memory: 1024
        cpuexecutioncap: 100
#  - name: ec2-ubuntu-12.04
#    driver:
#      name: ec2
#      region:  ap-northeast-1
#      availability_zone: ap-northeast-1c
#      flavor_id: t1.micro
#      image_id: ami-f397eef2
#      aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
#      aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
#      ssh_key: <%= ENV['AWS_SSH_KEY'] %>
#      aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
#      username: ubuntu
#      security_group_ids: ["<%= ENV['AWS_SECURITY_GROUP_ID'] %>"]
#      port: 22
#      ebs_optimized: false
#  - name: do-ubuntu-12.04
#    driver:
#      name: digitalocean
#      ssh_key: ~/.ssh/id_rsa
#    driver_config:
#      image_id: 3101045
#      region: San Francisco 1
#      flavor: 512MB
#      private_networking: false

suites:
  - name: rails
    run_list:
      - recipe[base::prepare]
      - recipe[build-essential]
      - recipe[git]
      - recipe[vim]
      - recipe[nginx]
      - recipe[mysql::server]
      - recipe[mysql::client]
      - recipe[ruby_build]
      - recipe[rbenv::system]
      - recipe[base]
      - recipe[base::rails]
    attributes:
      git:
        version: 1.9.1
      nginx:
        application_name: 'sample'
      mysql:
        server_debian_password: "passw0rd"
        server_root_password: "passw0rd"
        server_repl_password: "passw0rd"
      rbenv:
        rubies: ['2.1.0']
        global: '2.1.0'
        gems:
          '2.1.0':
            - name: 'bundler'
              options: '--no-ri --no-rdoc'
            - name: 'rails'
              options: '--no-ri --no-rdoc'
            - name: 'therubyracer'
              options: '--no-ri --no-rdoc'

