---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      name: vagrant
      network:
        - ["private_network", {ip: "192.168.33.33"}]
      synced_folders:
        - ["vagrant", "/usr/share/nginx", "create: true, type: :nfs"]
    provider: virtualbox
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
      customize:
        memory: 1024
        cpuexecutioncap: 100

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[git]
      - recipe[vim]
      - recipe[nginx]
      - recipe[mysql::server]
      - recipe[mysql::client]
      - recipe[ruby_build]
      - recipe[rbenv::system]
      - recipe[base]
    attributes:
      nginx:
        application_name: 'sample'
      mysql:
        server_debian_password: "passw0rd"
        server_root_password: "passw0rd"
        server_repl_password: "passw0rd"
      rbenv:
        rubies: ['2.1.0']
        global: '2.1.0'
        gems:
          '2.1.0':
            - name: 'bundler'
              options: '--no-ri --no-rdoc'
            - name: 'rails'
              options: '--no-ri --no-rdoc'
            - name: 'therubyracer'
              options: '--no-ri --no-rdoc'